env:
  browser: true
  node: true
extends: 'eslint:recommended'
rules:
  no-undef:
    - ignore
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
